import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
	// worker-configuration.d.ts is generated by `wrangler types` — never lint it
	{ ignores: ["dist", "worker-configuration.d.ts"] },
	{
		extends: [js.configs.recommended, ...tseslint.configs.recommended],
		files: ["**/*.{ts,tsx}"],
		languageOptions: {
			ecmaVersion: 2020,
			globals: globals.browser,
		},
		plugins: {
			"react-hooks": reactHooks,
			"react-refresh": reactRefresh,
		},
		rules: {
			...reactHooks.configs.recommended.rules,
			"react-refresh/only-export-components": [
				"warn",
				{ allowConstantExport: true },
			],
		},
	},
	{
		// Provider/adapter modules intentionally export hooks next to their component
		files: [
			"src/react-app/lib/providers/**/*.tsx",
			"src/react-app/lib/astryx/**/*.tsx",
		],
		rules: {
			"react-refresh/only-export-components": "off",
		},
	},
);
