export {
  ACCESS_TOKEN_COOKIE,
  AUTH_COOKIE,
  CSRF_COOKIE,
  REFRESH_COOKIE,
  clearSession,
  getPermissions,
  getToken,
  getTokenPayload,
  getUser,
  hasClientAudience,
  hasAuthCookie,
  hasPermission,
  hydrateSession,
  parseAccessToken,
  saveRefresh,
  saveSession,
  type SessionUser,
  type TokenPayload,
} from '@/shared/auth';
export { shouldBootstrapSession } from './lib/navigation';
export { CLIENT_API_ROUTES, withQuery } from '@/shared/api';
export {
  CLIENT_AUTH_ROUTES,
  CLIENT_PUBLIC_ROUTES,
  AUTHENTICATED_ENTRY_PATHS,
  DEFAULT_AUTHENTICATED_REDIRECT,
  LOGIN_RATE_LIMIT_COOKIE,
  LOGIN_NEXT_QUERY_PARAM,
  PUBLIC_ENTRY_PATHS,
  SESSION_TERMINATED_ROUTE,
  isAuthenticatedEntryPath,
  isPublicEntryPath,
  resolveAuthenticatedRedirect,
  sanitizeNextPath,
} from '@/shared/routing';
